### ISSUE TITLE
Feature Proposal: Checkbox for automatic preview on new seed

### ISSUE THREAD

**Issue by Larathiel** [jeheydorn/nortantis#12]
It would be nice if there was a toggle-able option to allow the automatic creation of the preview image whenever a new seed is entered/randomized.

Failing that, hotkeys for the buttons on the Terrain tab would be a decent alternative.

**Comment by Larathiel** [comment]
It does seem like a superfluous button, but I can see your point. Perhaps you could implement the auto-preview regen on a _detectable_ settings change, while relabeling the Preview button from "Preview" to "Refresh". That might be the best of both worlds and intuitive for those who get deep into the assets like you're talking.

**Comment by jeheydorn** [comment]
I reworked the entire UI of Nortantis, and one of those changes fixed this issue by removing the preview button and instead redrawing the map automatically when you make any change.
