### ISSUE TITLE
Export Heightmap

### ISSUE THREAD

**Issue by MalachiteDrake** [jeheydorn/nortantis#2]
I'm probably just being obtuse, but I can't get the map to export to anything. I click the 'Export Heightmap' button and...nothing happens. I'm running on Windows 10 and have Java completely updated. Everything else on the program works fine, I just can't actually _do_ anything with map once I have it completed. I checked the folder that Nortantis is stored in to make sure it wasn't creating a file there and just not telling me or something, but I can't find anything. I tried digging around on the website to see if there was anything telling you where to find the final file....I'm just completely lost at this point. Where does the final map get sent once you export it? Is it supposed to ask you to export it to somewhere specific? That's what I expected, but no other menu pops up or anything. It's like I haven't actually chosen something on the menu.

**Comment by jeheydorn** [comment]
The map gets stored as a temporary file and automatically opens in your
system's default image viewer. Perhaps your system's default image viewer
failed to open the file. One of the last messages logged by the generator
will give you the file name it get stored in, so you can try opening it in
another program.

If you don't see that file path in the generator's output, then please copy
paste the generator's output into this email and I'll take a look at it.

**Comment by MalachiteDrake** [comment]
Thanks for the reply!

I don't get any output. I click on 'Export Heightmap' and the only thing
that happens is the box under the Generate/Preview buttons goes blank if
there was anything in it.

Khris

**Comment by jeheydorn** [comment]
Well, that sounds bad. I've never seen that happen. Do you have the same
problem when generating regular maps? Or is it only height maps?

Try turning down the resolution on the background tab to the minimum of 25%
to see if this is an out of memory error, although I would be very
surprised if that was the issue because heightmaps take less memory to
generate than regular maps. If that doesn't work, you could try
redownloading and re-extracting the zip file in case it was corrupted in
transit.

**Comment by MalachiteDrake** [comment]
Turning the resolution down worked! Thanks!

**Comment by jeheydorn** [comment]
I'm glad it worked. If you still want to generate at higher resolutions,
you can work around this issue by giving the Java virtual machine more
memory. I have instructions on my web page for how to do that.

**Comment by jeheydorn** [comment]
I pushed a change a couple days ago which will cause this out of memory error to be less frequent and to give a meaningful error pop-up.
