### ISSUE TITLE
Memory allocation issues

### ISSUE THREAD

**Issue by amatsune** [jeheydorn/nortantis#5]
I tried alocating more memory but got this error:
Error occurred during initialization of VM
Could not reserve enough space for 2048000KB object heap

(my machine has 8GB, so shouldnt be a  problem)

Noticed that it runs in 32bit
Minecraft runs in 64bit and is able to use up 4 or more with no issues.

**Comment by jeheydorn** [comment]
You need to be running 64-bit Java to allocate more than about 2 GB of
memory for the Java virtual machine.

**Comment by amatsune** [comment]
Well, the program wasn’t running in 64 for whatever reason. Reinstalled both versions of java and it works now
