### ISSUE TITLE
Sand Dunes Aren't Drawn

### ISSUE THREAD

**Issue by rdedwards95** [jeheydorn/nortantis#8]
Hi there,

I'm getting a message when the map renders: 

Loading icon: assets\icons\sand\dunes\dune1.png
Loading icon: assets\icons\sand\dunes\dune2.png
Sand dunes will not be drawn because no sand dune images were found.

The map is able to render, but without sand dunes. I'm not sure what the issue is, those are the correct directories for the dune assets so it seems like the program knows where to look. Let me know if more information is helpful to provide.

Beautiful maps, I love what you've done here.

**Comment by jeheydorn** [comment]
It looks like I broke this in the master branch, but it's still working in
the version of the executable jar file is from, the one downloadable from
https://jeheydorn.github.io/nortantis/. I'll fix it when I get a chance,
but if you are running from source and want to use that version, I believe
it's 8b5f3a93d602233f139046c564268aef0e19e550

Just a note on what caused it - in IconDrawer.addSandDunes, this line:

List<Tuple2<BufferedImage, BufferedImage>> duneImages =
sandGroups.get("sand");

should be this:

List<Tuple2<BufferedImage, BufferedImage>> duneImages = sandGroups.get("
dunes");

**Comment by rdedwards95** [comment]
Awesome, I'll give this a go later today and let you know how it goes.

**Comment by rdedwards95** [comment]
Ok I ran it from source with the line corrected and it worked smoothly.

Thank you!
